parserOptions:
  ecmaVersion: 8

env:
  node: true
  es6: true
  browser: true

extends:
  - "eslint:recommended"

rules:
  # Disable some rules from eslint:recommended.
  no-console: "off"
  no-empty: ["error", { "allowEmptyCatch": true }]
  # Allow unused parameters. In callbacks, removing them seems to obscure
  # what the functions are doing.
  no-unused-vars: ["error", {"args": "none"}]

  # We use semicolons.
  semi: ["error", "always"]

  # We keep whitespace cleaned up.
  no-trailing-spaces: "error"
  eol-last: "error"
  object-curly-spacing: ["error", "always"]
  comma-dangle: ["error", "always-multiline"]
